#!/usr/bin/env bash
# this script displays "Best School" 10 times using while loop & if statement. ( the 9th iteration, displays Best School and then Hi on a new line.)

i=1
while [ $i -lt 11 ]
do
    if [ $i -eq 9 ]
      then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    (( i++ ))
done
