#!/usr/bin/env bash
# this script displays "Best School" 10 times using while loop & if statement

i=1
while [ $i -lt 11 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( i++ ))
done
