#!/usr/bin/env bash
# a Bash script that displays the content of the current directory
# in a list format where only the part of the name after the first

list=$(ls)
for file in $list; do
    echo "$file" | cut -d'-' -f2
done
