#!/usr/bin/env bash

# Install ufw if not already installed
sudo apt-get update
sudo apt-get install ufw

# Set default incoming policy to deny
sudo ufw default deny incoming

# allow ssh on port 22
sudo ufw allow 22/tcp

# allow http on port 80
sudo ufw allow 80/tcp

# allow https on port 443
sudo ufw allow 443/tcp

# enable ufw
sudo ufw enable